### ISSUE TITLE
ccu3-webui daemon.warn

### ISSUE THREAD

**Issue by gklank** [wolwin/WW-mySHT#1]
Hi,

just a warning but upcoming with every run of the "timer_USV-Monitor"-script, therefore every 5 minutes:

Jul 23 19:16:11 ccu3-webui daemon.warn cuxd[1467]: get_parameter 'CUX2801001:2.CMD_RUNS' not readable!
Jul 23 19:16:11 ccu3-webui daemon.warn cuxd[1467]: add_rpc_event(CUX2801001:2.CMD_RUNS = '') value undefined!

Is there any possibility to avoid this message?

Regards,

Gerhard
P.S.: this NUT function is very great, everythings looks functioning, one real power outage functioned perfectly...

**Comment by wolwin** [comment]
Hallo Gerhard,
ich antworte mal auf deutsch ... 
Die beiden Log-Zeilen sollten grundsätzlich gar nicht auftauchen - da die Warnmeldungen alle 5 Minuten auftauchen, nehme ich an, dass es sich um eine CCU3 mit NUT-Server Funktion handelt. Ich selber benutze eine Raspberrymatic ...
Der einzige Scriptunterschied: in der Warnmeldung wird der Kanal 2 benutzt - im Originalskript wird jedoch der Kanal 1 benutzt ... hast du alle Anpassungen auf Kanal 2 entsprechend vorgenommen?

Gruss Wolfram

**Comment by gklank** [comment]
Hallo wolwin,

vielen Dank für die schnelle Antwort.

Ich verwende auch  die Raspberrymatic mit der Firmwareversion 3.69.7.20230626.

Ich habe auf den Kanal 1 - wie in Deinem Original - wie auch mal auf Kanal 3 umgestellt, bekomme aber die gleiche Warnung.

Gibt es ggf. noch an der Auswahl des CUxD Gerätes noch etwas zu beachten?
Ich verwende in der CUxD das CUX2801001 als Switch, siehe Bild anbei:
![CUX2801001](https://github.com/wolwin/WW-mySHT/assets/73000462/3c29ef2d-55d5-471d-9f0a-0e33256693af)

Siehe ebenfalls anbei den Auszug aus dem "addons/xmlapi/statelist.cgi":
![xml](https://github.com/wolwin/WW-mySHT/assets/73000462/8932d96d-d8f1-493f-9a20-02fd44411d3d)


Grüße

Gerhard

**Comment by wolwin** [comment]
Hallo Gerhard,

die USV Scripte laufen auf z.Z. ohne Fehler auf drei Homematic / Raspberrymatic Systemen mit der Firmware 3.67.10.20230114 mit CuxD 2.10.1

Du hast statt des CuxD Kanal 1 die Exec-Funktionen auf den Kanal 2 gelegt - die Fehlermeldung deutet dabei eher auf einen Tippfehler oder einen Kopierfehler bei dieser Änderung / Installation hin:

![grafik](https://github.com/wolwin/WW-mySHT/assets/1790169/e2110eec-1155-428e-90f0-7dd4f887d6b9)

Im Original - also bei mir - wird Kanal 1 von CuxD benutzt:
![grafik](https://github.com/wolwin/WW-mySHT/assets/1790169/bf85bd62-6efc-4f97-95ee-78a0b212ad82)

Wenn Du den Kanal 2 benutzen willst, muß in den Skripten 'timer_USV-Monitor-Werte' und 'timer_USV-Werte' die '1' in eine '2' geändert werden
![grafik](https://github.com/wolwin/WW-mySHT/assets/1790169/430c84f9-2aee-495f-856b-18f1415d2a5c)

![grafik](https://github.com/wolwin/WW-mySHT/assets/1790169/bc277705-87ff-4036-a8ee-8f59b99df0a1)

Gruss Wolfram

**Comment by gklank** [comment]
Hallo Wolfram,

ja, muss ein Tippfehler gewesen sein.

Ich habe Deine Scripte einfach frisch reinkopiert und die beiden Stellen geändert.
Geht jetzt ohne Warnung...

Danke!!!

Gerhard
