### ISSUE TITLE
Basic prices monthly or yearly ?

### ISSUE THREAD

**Issue by Flieger37** [wolwin/WW-mySHT#2]
Hello,

could you please explain whether the **basic prices** ("Kosten Grundpreis") with which the script 'Uni-Zaehler_SysWrite.hms' must initially be filled are annual or monthly prices?

The price in the examples for gas appears to be the base monthly price. The electricity price appears to be the annual base price. Is that right?

Kind regards
Martin

**Comment by wolwin** [comment]
No,  the basic price ("Kosten Grundpreis") is the base price for one year.

**Comment by Flieger37** [comment]
Thank you very much for the clarification.

I have adapted it accordingly in my own documentation of the scripts and the presentation of the data in RaspberryMatic and Home Assistant, where I also display the data.
