### ISSUE TITLE
New Homematic "HmIP-ESI" energy counter 

### ISSUE THREAD

**Issue by Flieger37** [wolwin/WW-mySHT#3]
Hello,

I just bought the new Homematic "HmIP-ESI" energy counter to replace my Powerfox poweropti adapter.

Is it possible to integrate this device into the "Universal Homematic energy counter script"?

The output of the adapter looks like this (I already named it "Hausanschluss_ZS-Strom"):

<img width="508" alt="Bildschirmfoto 2023-12-14 um 17 18 23" src="https://github.com/wolwin/WW-mySHT/assets/65550366/ceb06d2f-ae1e-4bdc-beda-1e3332c87a8e">

<img width="514" alt="Bildschirmfoto 2023-12-14 um 17 17 27" src="https://github.com/wolwin/WW-mySHT/assets/65550366/03ab373b-caa8-4e5b-b2e8-481d5ab31737">

<img width="509" alt="Bildschirmfoto 2023-12-14 um 17 17 57" src="https://github.com/wolwin/WW-mySHT/assets/65550366/eb73bdd1-15c8-41a3-b4c3-05ec74d91575">

Regards
Martin

**Comment by wolwin** [comment]
Hi,
no - the script is designed for a 'HM-ES-TX-WM' - i.e. for the management of gas, electricity, water sensors that are connected to such a device.
The 'HmIP-ESI' is a pure electricity sensor that already has many features that are implemented in the script via code and system variables. It definitely makes no sense to adapt the script accordingly. It is better to write your own script for this.
Regards
Wolfram

**Comment by Flieger37** [comment]
Hi,

ok, thank you for your answer, which I fully understand.

Unfortunately, due to a lack of scripting and programming knowledge, I am not able to create such a great and detailed analysis of the values ​​as you did.

I find the universal approach of your script particularly interesting and with around 40 values you calculate far more and well selected values and sums (including the monetary ones) than the sensor generates (around 15).

I will continue to follow your project and would be very happy if you might change your mind sometimes.

Thanks for all the work you already did!
Martin
